/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import controladores.ControlDatos;
import estructuras.ListaEnlSim;
import javax.swing.JOptionPane;
import objetos.Usuario;

/**
 *
 * @author user-ubunto
 */
public class JFAdminUsuarios extends javax.swing.JFrame {

    private ControlDatos controlDatos;
    private ListaEnlSim<Usuario> usuarios;

    /**
     * Creates new form JFAdminUsuarios
     */
    public JFAdminUsuarios(ControlDatos controlDatos) {
        initComponents();
        this.controlDatos = controlDatos;
        usuarios = this.controlDatos.getTodosUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Administrador de Usuarios");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Agregar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Eliminar Usuario
        String idUsuario = JOptionPane.showInputDialog("Ingrese el codigo de usuario a modificar");
        Usuario usuarioM = this.controlDatos.buscarUsuarioEnArbol(idUsuario);
        ListaEnlSim ultimo = usuarios;
        if (usuarioM != null) {
            int index = 0;
            while (ultimo != null) {
                Object objErr = ultimo.getVal();
                if (objErr != null) {
                    Usuario usuarioE = (Usuario) objErr;
                    if (usuarioE.getNombreUsuario() == idUsuario) {                        
                        break;
                    }
                }
                index++;
                ultimo = ultimo.getSig();
            }
            usuarios.remove(index);
            this.controlDatos.insertarUsuariosEnArbol(usuarios);
            JOptionPane.showMessageDialog(null, "Usuario Eliminado");
        } else {
            JOptionPane.showMessageDialog(null, "El usuario no existe con ese id");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Modificar Usuario
        String idUsuario = JOptionPane.showInputDialog("Ingrese el codigo de usuario a modificar");
        Usuario usuarioM = this.controlDatos.buscarUsuarioEnArbol(idUsuario);
        if (usuarioM != null) {
            String idUsuarioNuevo = JOptionPane.showInputDialog("Ingrese el nuevo codigo de usuario");
            Usuario usuarioN = this.controlDatos.buscarUsuarioEnArbol(idUsuarioNuevo);
            if (usuarioN == null) {
                //ModificarUsuario
                usuarioM.setNombreUsuario(idUsuarioNuevo);
                this.controlDatos.insertarUsuariosEnArbol(usuarios);
                JOptionPane.showMessageDialog(null, "Usuario: " + idUsuario + " modificado a " + idUsuarioNuevo);
            } else {
                JOptionPane.showMessageDialog(null, "El usuario ya existe con ese id");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El usuario no existe con ese id");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Agregar Usuario
        String idUsuarioNuevo = JOptionPane.showInputDialog("Ingrese el codigo de usuario a ingresar");
        Usuario usuarioN = this.controlDatos.buscarUsuarioEnArbol(idUsuarioNuevo);
        if (usuarioN == null) {
            this.controlDatos.insertarNuevoUsuario(idUsuarioNuevo);
            JOptionPane.showMessageDialog(null, "Usuario: " + idUsuarioNuevo + " insertado");
        } else {
            JOptionPane.showMessageDialog(null, "El usuario ya existe con ese id");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
