
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symC {
  /* terminals */
  public static final int COMA = 4;
  public static final int NUM = 2;
  public static final int CORCHD = 7;
  public static final int HEXA = 3;
  public static final int error = 1;
  public static final int PUNT_COMA = 5;
  public static final int CORCHI = 6;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "HEXA",
  "COMA",
  "PUNT_COMA",
  "CORCHI",
  "CORCHD"
  };
}

