
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class symU {
  /* terminals */
  public static final int DOS_PUNT = 5;
  public static final int COMA = 4;
  public static final int NUM = 2;
  public static final int NOMU = 3;
  public static final int error = 1;
  public static final int PUNT_COMA = 6;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "NOMU",
  "COMA",
  "DOS_PUNT",
  "PUNT_COMA"
  };
}

